services:
  - type: web
    plan: free
    name: repo-explainer
    runtime: python
    repo: https://github.com/BaoNguyen09/repo-explainer
    buildCommand: 'pip install -e .'
    startCommand: 'fastapi run backend/main.py --host 0.0.0.0 --port $PORT'