services:
  - type: web
    plan: free
    name: repo-explainer
    runtime: python
    repo: https://github.com/BaoNguyen09/repo-explainer
    buildCommand: 'cd backend && pip install -r requirements.txt'
    startCommand: 'cd backend && fastapi run --host 0.0.0.0 --port $PORT'